name: Build and Deploy Service

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to GitHub Registry
        uses: velddev/gp-docker-action@v0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: yagami
          image-tag: ${{ github.run_id }}
          dockerfile-path: Dockerfile
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: Azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v1.2
        with:
          namespace: yagami
          imagepullsecrets: |
            github-pull-secret
          manifests: |
            .kube/deployment.yml
            .kube/service.yml
          images: ghcr.io/veldtech/yagami/yagami:${{ github.run_id }}
